Repository TEAM-gimhanul/back-end, pull requests merged in 2021-11, with the labels that each got.

#3 🔀 :: (#2) CI, CD 구축
  .github/workflows/CD.yml
  .github/workflows/CI.yml
Labels: 기능

#8 Swagger config 설정
  src/main/java/com/backend/gimhanul/domain/.gitkeep
  src/main/java/com/backend/gimhanul/global/config/SwaggerConfig.java
Labels: 설정

#10 🔀 :: Socketio 기본 설정
  build.gradle
  src/main/java/com/backend/gimhanul/global/config/SocketConfig.java
  src/main/java/com/backend/gimhanul/global/config/properties/SocketProperties.java
  src/main/java/com/backend/gimhanul/global/socket/SocketProperty.java
  src/main/java/com/backend/gimhanul/global/socket/SocketRunner.java
  src/main/java/com/backend/gimhanul/global/socket/WebSocketAddMappingSupporter.java
  src/main/java/com/backend/gimhanul/global/socket/annotation/SocketController.java
  src/main/java/com/backend/gimhanul/global/socket/annotation/SocketMapping.java
  src/main/java/com/backend/gimhanul/global/socket/exception/SocketExceptionListener.java
  src/main/java/com/backend/gimhanul/global/socket/security/AuthenticationProperty.java
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketConnectController.java
  src/main/resources/application.yml
Labels: 설정

#15 Add: User Entity & Repository & Serivce
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
  src/main/java/com/backend/gimhanul/domain/user/domain/repositories/UserRepository.java
  src/main/java/com/backend/gimhanul/domain/user/service/UserService.java
Labels: 설정

#25 Feat/room entity&repository&service
  src/main/java/com/backend/gimhanul/domain/room/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/room/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/room/services/RoomSerivce.java
Labels: 설정

#26 🔀 :: Spring cloud openfeign 설정
  build.gradle
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
  src/main/java/com/backend/gimhanul/global/utils/api/FeignClientErrorDecoder.java
  src/main/java/com/backend/gimhanul/global/utils/api/FeignConfiguration.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/.gitkeep
  src/main/java/com/backend/gimhanul/global/utils/api/dto/.gitkeep
  src/main/java/com/backend/gimhanul/global/utils/api/exception/OtherServerBadRequestException.java
  src/main/java/com/backend/gimhanul/global/utils/api/exception/OtherServerExpiredTokenException.java
  src/main/java/com/backend/gimhanul/global/utils/api/exception/OtherServerForbiddenException.java
  src/main/java/com/backend/gimhanul/global/utils/api/exception/OtherServerUnauthorizedException.java
Labels: 설정

#28 Add: member entity & repository & service
  src/main/java/com/backend/gimhanul/domain/member/domain/Member.java
  src/main/java/com/backend/gimhanul/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/backend/gimhanul/domain/member/service/MemberService.java
  src/main/java/com/backend/gimhanul/domain/room/service/RoomSerivce.java
Labels: 설정

#30 Fix: member, room 엔티티 PK AI설정
  src/main/java/com/backend/gimhanul/domain/member/domain/Member.java
  src/main/java/com/backend/gimhanul/domain/room/domain/Room.java
Labels: 설정

#33 🔀 :: 카카오 로그인 링크 가져오기
  build.gradle
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/service/QueryKakaoAuthLinkService.java
  src/main/java/com/backend/gimhanul/domain/user/service/UserService.java
  src/main/java/com/backend/gimhanul/global/config/properties/UserProperties.java
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketConnectController.java
  src/main/resources/application.yml
Labels: 기능

#34 Fix: entity builder & user profile
  src/main/java/com/backend/gimhanul/domain/member/domain/Member.java
  src/main/java/com/backend/gimhanul/domain/message/domain/Message.java
  src/main/java/com/backend/gimhanul/domain/room/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
Labels: 리펙토링

#35 Fix: chatting 관련 엔티티 & 정리 & authInterceptor 틀 추가
  src/main/java/com/backend/gimhanul/domain/chat/domain/Member.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/Message.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MemberRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MessageRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/member/service/MemberService.java
  src/main/java/com/backend/gimhanul/domain/message/service/MessageService.java
  src/main/java/com/backend/gimhanul/domain/room/service/RoomSerivce.java
  src/main/java/com/backend/gimhanul/global/annotation/UserLoginToken.java
  src/main/java/com/backend/gimhanul/global/interceptor/AuthInterceptor.java
Labels: 설정

#36 🔀 :: 구글 로그인 링크 가져오기
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/service/QueryGoogleAuthLinkService.java
  src/main/java/com/backend/gimhanul/domain/user/service/QueryKakaoAuthLinkService.java
  src/main/java/com/backend/gimhanul/global/config/properties/UserProperties.java
  src/main/resources/application.yml
Labels: 기능

#37 🔀 :: 네이버 로그인 링크 가져오기
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/service/QueryNaverAuthLinkService.java
  src/main/java/com/backend/gimhanul/global/config/properties/UserProperties.java
  src/main/resources/application.yml
Labels: 기능

#38 Add: token provider
  src/main/java/com/backend/gimhanul/global/config/properties/JwtProperties.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
  src/main/java/com/backend/gimhanul/global/exceptions/ServerErrorException.java
  src/main/java/com/backend/gimhanul/global/security/jwt/JwtTokenProvider.java
  src/main/java/com/backend/gimhanul/global/security/jwt/exception/TokenBadRequestException.java
  src/main/java/com/backend/gimhanul/global/security/jwt/exception/TokenExpireException.java
  src/main/java/com/backend/gimhanul/global/security/jwt/exception/TokenForgedException.java
  src/main/resources/application.yml
Labels: 기능

#39 🔀 :: 네이버 로그인
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
  src/main/java/com/backend/gimhanul/domain/user/exception/CredentialsNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/presentation/dto/request/AuthRequest.java
  src/main/java/com/backend/gimhanul/domain/user/presentation/dto/response/TokenResponse.java
  src/main/java/com/backend/gimhanul/domain/user/service/NaverAuthService.java
  src/main/java/com/backend/gimhanul/domain/user/service/QueryNaverAuthLinkService.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/NaverAuthClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/NaverInfoClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/response/NaverInformationResponse.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/response/NaverTokenResponse.java
Labels: 기능

#41 Add: validate token to get user
  src/main/java/com/backend/gimhanul/domain/user/exception/UserNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/user/facade/UserFacade.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
  src/main/java/com/backend/gimhanul/global/interceptor/TokenInterceptor.java
  src/main/java/com/backend/gimhanul/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 리펙토링

#42 🔀 :: 구글 로그인
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/service/GoogleAuthService.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/GoogleAuthClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/GoogleInfoClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/NaverAuthClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/request/GoogleCodeRequest.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/response/GoogleInformationResponse.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/response/TokenResponse.java
Labels: 기능

#43 🔀 :: 카카오 로그인
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
  src/main/java/com/backend/gimhanul/domain/user/service/KakaoAuthService.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/KakaoAuthClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/client/KakaoInfoClient.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/request/KakaoCodeRequest.java
  src/main/java/com/backend/gimhanul/global/utils/api/dto/response/KakaoInformationResponse.java
Labels: 기능

#45 🔀 :: OAuth 토큰 발급 로직
  src/main/java/com/backend/gimhanul/domain/user/service/GoogleAuthService.java
  src/main/java/com/backend/gimhanul/domain/user/service/KakaoAuthService.java
  src/main/java/com/backend/gimhanul/domain/user/service/NaverAuthService.java
Labels: 기능

#50 🔀 :: 채팅 보내기
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MemberRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MessageRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/MemberNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/RoomNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/.gitkeep
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/request/SendChatRequest.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/domain/user/facade/UserFacade.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
Labels: 기능

#51 🔀 :: 소켓 방 구독
  src/main/java/com/backend/gimhanul/domain/chat/exception/InvalidArgumentException.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
Labels: 기능

#52 🔀 :: 소켓 모든 방 구독
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SubscribeAllService.java
Labels: 기능

#57 🔀 :: 소켓 인증
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketConnectController.java
Labels: 기능

#60 Add: Interceptor config
  src/main/java/com/backend/gimhanul/global/config/InterceptorConfig.java
Labels: 설정

#59 🔀 :: 랜덤 방 입장
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MemberRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/JoinResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/JoinRoomService.java
  src/main/java/com/backend/gimhanul/domain/user/domain/repositories/UserRepository.java
Labels: 기능

#61 Fix: yml data
  src/main/resources/application.yml
Labels: 버그

#63 🔀 :: 방 가져오기
  src/main/java/com/backend/gimhanul/domain/chat/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/QueryRoomResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryRoomService.java
Labels: 기능

#64 Main merge
  src/main/java/com/backend/gimhanul/domain/chat/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MemberRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MessageRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/RoomRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/InvalidArgumentException.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/MemberNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/RoomNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/.gitkeep
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/request/SendChatRequest.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/JoinResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/QueryRoomResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/JoinRoomService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryRoomService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SubscribeAllService.java
  src/main/java/com/backend/gimhanul/domain/user/domain/repositories/UserRepository.java
  src/main/java/com/backend/gimhanul/domain/user/facade/UserFacade.java
  src/main/java/com/backend/gimhanul/global/config/InterceptorConfig.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketConnectController.java
  src/main/resources/application.yml
Labels: 배포

#66 Add: get my info
  src/main/java/com/backend/gimhanul/domain/user/presentation/UserController.java
Labels: 기능

#70 🔀 :: CORS
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MessageRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/ChatController.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/.gitkeep
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/request/SendChatRequest.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/QueryMessageResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryMessageService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/global/config/WebConfig.java
Labels: 설정

#74 🔀 :: 방 가져오기 ProfileImage
  src/main/java/com/backend/gimhanul/domain/chat/domain/Room.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/QueryRoomResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryRoomService.java
Labels: 기능

#76 Add: emoji Entity & getRandomEmoji
  src/main/java/com/backend/gimhanul/domain/chat/domain/Emoji.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/EmojiRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/EmojiNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/EmojiFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/MemberFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/RoomFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/service/GetRandomEmojiService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryMessageService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
Labels: 기능

#77 Develop
  src/main/java/com/backend/gimhanul/domain/chat/domain/Emoji.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/EmojiRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/EmojiNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/EmojiFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/MemberFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/facade/RoomFacade.java
  src/main/java/com/backend/gimhanul/domain/chat/service/GetRandomEmojiService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryMessageService.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
Labels: 배포

#83 🔀 :: 소켓 join 프로필 이미지
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/JoinResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/JoinRoomService.java
Labels: 기능

#84 🔀 :: 메세지 시간 저장
  src/main/java/com/backend/gimhanul/GimhanulApplication.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/Message.java
Labels: 기능

#86 🔀 :: 채팅방 리스트 최근 메세지
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/MessageRepository.java
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/QueryRoomResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/QueryRoomService.java
Labels: 기능

#87 🔀 :: 욕설 캐싱 엔티티
  src/main/java/com/backend/gimhanul/domain/chat/domain/Swear.java
  src/main/java/com/backend/gimhanul/domain/chat/domain/repository/SwearRepository.java
Labels: 기능

#89 Add: KR filter
  src/main/java/com/backend/gimhanul/global/utils/CheckExist.java
Labels: 버그, 기능

#90 🔀 :: 욕설 캐싱
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
Labels: 기능

#92 Add: check eng
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
Labels: 버그, 기능

#95 🔀 :: 욕설 대체값 지정
  src/main/java/com/backend/gimhanul/domain/chat/domain/Swear.java
  src/main/java/com/backend/gimhanul/domain/chat/exception/SwearNotFoundException.java
  src/main/java/com/backend/gimhanul/domain/chat/service/SendChatService.java
  src/main/java/com/backend/gimhanul/global/errors/exception/ErrorCode.java
Labels: 기능

#96 🔀 :: sentAt 값
  src/main/java/com/backend/gimhanul/domain/chat/domain/Message.java
Labels: 버그

#99 🔀 :: 유저 온라인 여부
  src/main/java/com/backend/gimhanul/domain/chat/presentation/dto/response/JoinResponse.java
  src/main/java/com/backend/gimhanul/domain/chat/service/JoinRoomService.java
  src/main/java/com/backend/gimhanul/domain/user/domain/User.java
  src/main/java/com/backend/gimhanul/global/config/SocketConfig.java
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketConnectController.java
  src/main/java/com/backend/gimhanul/global/socket/security/WebSocketDisConnectController.java
Labels: 기능
